
services:

# 1. Service de gestion des séries
  series-service:
    build: ./series-service
    container_name: series-service
    ports:
      - "8000:8000"
    volumes:
      - ./series-service:/app
    restart: always

# 2. Service de gestion des utilisateurs

# frontend
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "5500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    restart: always