server {
    listen 80;

    # 1. Fichiers statiques frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    # 2. Requêtes vers series-service
    location /api {
        proxy_pass http://series-service:8000;
    }

    # 3. Requêtes vers user-service
    location /users {
        proxy_pass http://user-service:8000;
    }
}