server {
    listen 80;

    # 1. On affiche ton site web (HTML, CSS, JS) pour tout le reste
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
    }

    # 2. Le secret est ici : on route les requêtes API vers ton backend Python
    location /api {
        # Attention : PAS de slash (/) à la fin de cette ligne !
        proxy_pass http://series-service:8000;
    }
}