# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: series.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'series.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cseries.proto\x12\x06series\"\"\n\rSeriesRequest\x12\x11\n\tseries_id\x18\x01 \x01(\x05\"1\n\x0eSeriesResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2U\n\x0fSeriesValidator\x12\x42\n\x11\x43heckSeriesExists\x12\x15.series.SeriesRequest\x1a\x16.series.SeriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'series_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERIESREQUEST']._serialized_start=24
  _globals['_SERIESREQUEST']._serialized_end=58
  _globals['_SERIESRESPONSE']._serialized_start=60
  _globals['_SERIESRESPONSE']._serialized_end=109
  _globals['_SERIESVALIDATOR']._serialized_start=111
  _globals['_SERIESVALIDATOR']._serialized_end=196
# @@protoc_insertion_point(module_scope)
