apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      serviceAccountName: user-service-sa
      containers:
        - name: user-service
          image: myrafilia/user-service:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            # Connexion au réseau interne K8s
            - name: POSTGRES_HOST
              value: postgres-service
            - name: POSTGRES_DB
              value: userdb
            - name: SECRET_KEY
              value: dev_secret_key_change_in_production
            # Récupération sécurisée depuis le Secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          livenessProbe:
            httpGet:
              path: /users/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10