apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: series-service-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: favorites-service-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: review-service-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: default
---